### ISSUE TITLE
Aux output COM port Only one usage of socket address error

### ISSUE THREAD

**Issue by AaronOcchipintiKCi** [Kingfisher-Company-Inc/BugReportForms#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### There is no customer sensitive data in this bug report!

- [X] I AM 100% SURE THERE IS NO CUSTOMER SENSITIVE DATA!!!

### Current Behavior

If you select COM port 1 for "COM Port Selected:" and then enable "AUX Relay Extension Board" and also select COM port 1, you will get an error message "Relay COM port is the same as AUX COM port. And the COM part is enabled. Current action is aborted" (first off is should say port, not part) secondly it will allow you to save and say "AUX output settings saved" even after prompting you with that warning...

### Expected Behavior

It should not allow you to use the same COM port for Relay and AUX. The warning message should most likely say "port" not "part" and if that warning appears the AUX output / COM port settings should not be saved!

### Steps To Reproduce

1.) Enable COM output, and select COM port 1
2.) Enable the AUX Relay Extension Board and also select COM port 1 (will happen by default if you only have one COM port on PC)
3.) Click Save

### Version

0.1.37

### What is the system configured as?

Server

### What Operating System are you seeing the problem on?

Windows 11

### What SQL Version are you seeing the problem on?

2022

### Double check that there is no customer sensitive data in this bug report!

- [X] I AM 200% SURE THERE IS NO CUSTOMER SENSITIVE DATA!!!

**Comment by AaronOcchipintiKCi** [comment]
The relevant log output: 

2024-01-19 11:06:08.809 -08:00 [ERR] System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at NextGenGui.AuxOutput.AuxOutputIPSocketThread.<Start>b__16_0(Object async) in C:\GithubAaron\NextGenGUI\MainBuild\AuxOutput\AuxOutputIPSocketThread.cs:line 195
